server:
  port: 8081
spring:
  application:
    name:
      ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alidi1011/project_configurations.git
eureka:
  client:
    region: default
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5